kind: pipeline
type: docker
name: unit tests

steps:
  - name: go vet and unit tests
    image: golang:1.19
    commands:
      - echo "hey"
      - exit 2
      - echo "done"
    depends_on:
      - clone
