kind: pipeline
type: docker
name: change-exit-status

steps:
  - name: generate-script
    image: alpine
    commands:
      - echo '#!/bin/sh' > custom_script.sh
      - echo 'exit 2' >> custom_script.sh
      # Make the script executable
      - chmod +x custom_script.sh

  - name: execute-script
    image: alpine
    commands:
      - . ./custom_script.sh > script_output.txt 2>&1 || true  # Redirect output to file and ignore errors
      # Capture the exit status of the script
      - script_exit_status=$?
      - if [ $script_exit_status -eq 2 ]; then exit 1; fi
