kind: pipeline
type: docker
name: unit tests

steps:
  - name: go vet and unit tests
    image: golang:1.17
    commands:
      - go vet ./...
      - go test -cover ./...
      - go build -o release/linux/amd64/lite-engine
    volumes:
      - name: cache
        path: /go
    depends_on:
      - clone
  - name: golangci-lint
    image: golangci/golangci-lint
    commands:
      - golangci-lint run --timeout 300s
    volumes:
      - name: cache
        path: /go
    depends_on:
      - clone

volumes:
  - name: cache
    temp: {}

# ---
# kind: pipeline
# type: aws
# name: ubuntu acceptance tests

# pool:
#   use: ubuntu

# steps:
#   - name: build
#     image: golang:1.17
#     commands:
#       - GOOS=linux   GOARCH=amd64   go build -ldflags "-X main.version=${DRONE_TAG##v}" -o release/linux/amd64/lite-engine
#   - name: server
#     detach: true
#     commands:
#       - touch .env
#       - ./release/linux/amd64/lite-engine certs
#       - ./release/linux/amd64/lite-engine server
#     depends_on:
#       - build
#   - name: run certs client
#     commands:
#       - sleep 5
#       - ./release/linux/amd64/lite-engine client
#     depends_on:
#       - server

---
kind: pipeline
type: docker
name: release artifacts

steps:
  - name: build
    image: golang:1.17
    commands:
      - GOOS=linux   GOARCH=amd64   go build -ldflags "-X main.version=${DRONE_TAG##v}" -o release/lite-engine-linux-amd64
      - GOOS=linux   GOARCH=arm64   go build -ldflags "-X main.version=${DRONE_TAG##v}" -o release/lite-engine-linux-arm64
      - GOOS=darwin  GOARCH=amd64   go build -ldflags "-X main.version=${DRONE_TAG##v}" -o release/lite-engine-darwin-amd64
      - GOOS=darwin  GOARCH=arm64   go build -ldflags "-X main.version=${DRONE_TAG##v}" -o release/lite-engine-darwin-arm64
      - GOOS=windows GOARCH=amd64   go build -ldflags "-X main.version=${DRONE_TAG##v}" -o release/lite-engine-windows-amd64.exe

  - name: release
    image: plugins/github-release
    settings:
      files:
        - release/lite-engine-linux-amd64
        - release/lite-engine-linux-arm64
        - release/lite-engine-darwin-amd64
        - release/lite-engine-darwin-arm64
        - release/lite-engine-windows-amd64.exe
      api_key:
        from_secret: github_token
trigger:
  event:
    - tag
