kind: pipeline
type: docker
name: unit tests

steps:
  - name: go vet and unit tests
    image: golang:1.19
    commands:
      - touch a.sh
      - echo "exit 2" >> a.sh
      - chmod +x a.sh
      - ./a.sh
    depends_on:
      - clone
