kind: pipeline
type: docker
name: unit tests

steps:
  - name: go vet and unit tests
    image: golang:1.19
    commands:
      - echo "hey"
      - touch a.sh
      - echo "exit 2" >> a.sh
      - chmod +x a.sh
      - . ./a.sh
      - echo "done"
      - script_exit_status=$?
      - if [ $script_exit_status -eq 2 ]; then exit 1; fi
    depends_on:
      - clone
