kind: pipeline
type: docker
name: change-exit-status

steps:
  - name: generate-script
    image: alpine
    commands:
      - echo '#!/bin/sh' > custom_script.sh
      - echo 'exit 2' >> custom_script.sh
      # Make the script executable
      - chmod +x custom_script.sh

  - name: execute-script
    image: alpine
    commands:
      - ./custom_script.sh; output=$? || true
      - if [ $output -eq 2 ]; then exit 1; fi
